chat_model:
  name: "meta/llama3-8b-instruct"

  # AI Catalog
  url: "https://integrate.api.nvidia.com/v1"

  # Locally running NIM
  # url: "http://llm-nim-0:8000/v1"

# Milvus and Redis have been configured with env variables.
